### ISSUE TITLE
gt_obj.txt file issue

### ISSUE THREAD

**Issue by hic9507** [apphia39/kor_crnn#1]
안녕하세요, velog에 작성해주신 글을 보고 실습을 하다가 get_images.py를 실행할 시에 문제가 생겨서 질문 드립니다.
일단 매뉴얼대로 따라한 후 gt_train, test, validation.txt 파일을 보면 

test/00104601.png	횡단송수관로 누수발생사고도 인재다. 구미시는 5월 16일 문서로 낙test/00104617.png	1년 만에 재개됐습니다. CJ그룹 이미경 부회장 퇴진을 압박한 혐읩니test/00104622.png	찾는 이들이 많다. 하지만 여름 보양식에 와인을 곁들이면 더욱 좋다test/00104631.png	김두관 경남도지사가 '여소야대'로 곤욕을 치르고 있다. 최근 한나라test/00104634.png	약인 '모자이크프로젝트사업'과 '인공습지조성사업' 관련 예산이 포test/00104639.png	

이런 식으로 tab이 이상하게 되어있습니다. 그래서 get_images.py를 실행하면 train, test, validation 모두 첫 줄에서 텍스트가 다 읽히고각각 사진 한 장씩만 폴더에 들어갑니다.
gt_obj.txt 파일 생성 시에 문장이 밀려들어가서 그런 것 같은데, 혹시 이런 문제는 어떻게 해결해야 하나요?

**Comment by apphia39** [comment]
안녕하세요!

너무 늦게 확인했네요 죄송합니다ㅠㅠ

`aihub_dataset.py`에서 gt file 작성하는 부분에 오타가 있었습니다. 
맨 마지막에 gt_file.write하는부분 마지막에 \n 추가해주시면 됩니다.
깃헙에도 업데이트 해두었습니다:)

문제가 해결되지 않으면 다시 이슈 남겨주시거나 **apphia39@naver.com**으로 메일 주세요!
